import type { Metadata } from "next";
import { Figtree, Geist, Manrope } from "next/font/google";
import "../globals.css"; // Perhatikan path naik satu level (../)
import LenisScrollProvider from "../LenisProvider"; // Sesuaikan path jika perlu
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Suspense } from "react";
import TopLoadingBar from "@/components/TopLoadingBar";
import GlobalAlert from "@/components/dashboard/GlobalAlert";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Shortlinkmu",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} className="scroll-smooth">
      <body
        className={`${figtree.className} ${manrope.className} ${geist.className} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <LenisScrollProvider>
            <Suspense fallback={null}>
              <TopLoadingBar />
            </Suspense>
            <GlobalAlert /> {/* <--- 2. PASANG DISINI */}
            {children}
          </LenisScrollProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
