import type { Metadata } from "next";
import { Figtree, Geist } from "next/font/google";
import "@/app/globals.css";
import LenisScrollProvider from "../LenisProvider";
import { NextIntlClientProvider } from "next-intl"; // [TAMBAH]
import { getMessages } from "next-intl/server"; // [TAMBAH]

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// [UBAH] Ubah RootLayout jadi async dan terima 'locale'
export default async function RootLayout({
  children,
  params: { locale }, // [TAMBAH]
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string }; // [TAMBAH]
}>) {
  // [TAMBAH] Ambil messages untuk provider
  const messages = await getMessages();

  return (
    // [UBAH] Tambahkan 'locale' ke <html>
    <html lang={locale} className="scroll-smooth">
      <body className={` ${figtree.className} ${geist.className} antialiased`}>
        {/* [UBAH] Bungkus LenisProvider dengan NextIntlClientProvider */}
        <NextIntlClientProvider locale={locale} messages={messages}>
          <LenisScrollProvider>{children}</LenisScrollProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
