import type { Metadata } from "next";
import { Figtree, Geist } from "next/font/google";
import "../globals.css"; // Perhatikan path naik satu level (../)
import LenisScrollProvider from "../LenisProvider"; // Sesuaikan path jika perlu
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Shortlinkmu",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Pastikan locale valid
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Ambil semua pesan terjemahan di sisi server
  const messages = await getMessages();

  return (
    <html lang={locale} className="scroll-smooth">
      <body className={`${figtree.className} ${geist.className} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <LenisScrollProvider>{children}</LenisScrollProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
